export const REQUEST_AUTH = 'REQUEST_AUTH'
export const REQUEST_AUTH_SUCCESS = 'REQUEST_AUTH_SUCCESS'

export const GET_SESSION = 'GET_SESSION'
export const GET_SESSION_SUCCESS = 'GET_SESSION_SUCCESS'